// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.4.0
// - protoc             v5.27.2
// source: agent.proto

package rpcEngine

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	Services_Messaging_FullMethodName = "/rpcEngine.Services/Messaging"
)

// ServicesClient is the client API for Services service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ServicesClient interface {
	Messaging(ctx context.Context, opts ...grpc.CallOption) (Services_MessagingClient, error)
}

type servicesClient struct {
	cc grpc.ClientConnInterface
}

func NewServicesClient(cc grpc.ClientConnInterface) ServicesClient {
	return &servicesClient{cc}
}

func (c *servicesClient) Messaging(ctx context.Context, opts ...grpc.CallOption) (Services_MessagingClient, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Services_ServiceDesc.Streams[0], Services_Messaging_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &servicesMessagingClient{ClientStream: stream}
	return x, nil
}

type Services_MessagingClient interface {
	Send(*Message) error
	Recv() (*Message, error)
	grpc.ClientStream
}

type servicesMessagingClient struct {
	grpc.ClientStream
}

func (x *servicesMessagingClient) Send(m *Message) error {
	return x.ClientStream.SendMsg(m)
}

func (x *servicesMessagingClient) Recv() (*Message, error) {
	m := new(Message)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ServicesServer is the server API for Services service.
// All implementations must embed UnimplementedServicesServer
// for forward compatibility
type ServicesServer interface {
	Messaging(Services_MessagingServer) error
	mustEmbedUnimplementedServicesServer()
}

// UnimplementedServicesServer must be embedded to have forward compatible implementations.
type UnimplementedServicesServer struct {
}

func (UnimplementedServicesServer) Messaging(Services_MessagingServer) error {
	return status.Errorf(codes.Unimplemented, "method Messaging not implemented")
}
func (UnimplementedServicesServer) mustEmbedUnimplementedServicesServer() {}

// UnsafeServicesServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ServicesServer will
// result in compilation errors.
type UnsafeServicesServer interface {
	mustEmbedUnimplementedServicesServer()
}

func RegisterServicesServer(s grpc.ServiceRegistrar, srv ServicesServer) {
	s.RegisterService(&Services_ServiceDesc, srv)
}

func _Services_Messaging_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ServicesServer).Messaging(&servicesMessagingServer{ServerStream: stream})
}

type Services_MessagingServer interface {
	Send(*Message) error
	Recv() (*Message, error)
	grpc.ServerStream
}

type servicesMessagingServer struct {
	grpc.ServerStream
}

func (x *servicesMessagingServer) Send(m *Message) error {
	return x.ServerStream.SendMsg(m)
}

func (x *servicesMessagingServer) Recv() (*Message, error) {
	m := new(Message)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Services_ServiceDesc is the grpc.ServiceDesc for Services service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Services_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "rpcEngine.Services",
	HandlerType: (*ServicesServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Messaging",
			Handler:       _Services_Messaging_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "agent.proto",
}
