monitor:
  interval_seconds: 600
  grpc_port: 50051
  sensitive_dirs:
    - /windows/system32
    - /windows/syswow64

threat_intel:
  feeds:
    - path: ./data/malware_hashes.json
      format: json
